global:
  edition: ce
  hosts:
    domain: gitlab.example.com
    https: false
    externalIP: ""
  
  ingress:
    configureCertmanager: false
    enabled: false
    tls:
      enabled: false
  
  minio:
    enabled: false
  
  gitaly:
    enabled: true
  
  psql:
    host: "dev-db.cyxw2mqqud77.us-east-1.rds.amazonaws.com"
    port: 5432
    database: "mydatabase"
    username: "dbadmin"
    password:
      secret: "gitlab-postgres-secret"
      key: "password"
    ssl:
      enabled: false
      secret: "gitlab-ssl-dummy"
      serverCA: "dummy-server-ca.pem"
      clientKey: "dummy-client.key"
      clientCertificate: "dummy-client.crt"

  appConfig:
    artifacts:
      enabled: false
      object_store:
        enabled: false
        connection:
          secret: "gitlab-object-storage-dummy"
          key: "connection"
    lfs:
      enabled: false
      object_store:
        enabled: false
        connection:
          secret: "gitlab-object-storage-dummy"
          key: "connection"
    uploads:
      enabled: false
      object_store:
        enabled: false
        connection:
          secret: "gitlab-object-storage-dummy"
          key: "connection"
    packages:
      enabled: false
      object_store:
        enabled: false
        connection:
          secret: "gitlab-object-storage-dummy"
          key: "connection"
    backups:
      enabled: false
      object_store:
        enabled: false
        connection:
          secret: "gitlab-object-storage-dummy"
          key: "connection"

certmanager:
  install: false

nginx-ingress:
  enabled: false

postgresql:
  install: false

redis:
  install: true

gitlab-runner:
  install: false

gitlab:
  toolbox:
    enabled: false
    backups:
      objectStorage:
        enabled: false

  webservice:
    enabled: true

  sidekiq:
    enabled: true

  gitlab-shell:
    enabled: true

  rails:
    migrations:
      enabled: true
