global:
  edition: ce
  hosts:
    domain: gitlab.example.com
    https: false
    gitlab:
      name: "GitLab CE"
    ingress:
      configureCertmanager: false

  # Service Account Configuration
  serviceAccount:
    enabled: true
    create: true
    name: gitlab-serviceaccount
    automountServiceAccountToken: false
    labels: {}
    annotations: {}

  communityImages:
    migrations:
      repository: registry.gitlab.com/gitlab-org/build/cng/gitlab-toolbox-ce
    sidekiq:
      repository: registry.gitlab.com/gitlab-org/build/cng/gitlab-sidekiq-ce
    toolbox:
      repository: registry.gitlab.com/gitlab-org/build/cng/gitlab-toolbox-ce
    webservice:
      repository: registry.gitlab.com/gitlab-org/build/cng/gitlab-webservice-ce
    workhorse:
      repository: registry.gitlab.com/gitlab-org/build/cng/gitlab-workhorse-ce

  psql:
    password:
      secret: gitlab-postgres
      key: password
  redis:
    password:
      enabled: false

webservice:
  tests:
    enabled: false
  serviceAccount:
    enabled: true
    create: true
    labels: {}
    annotations: {}

gitlab-runner:
  enabled: false

postgresql:
  image:
    tag: "13.6"
  persistence:
    enabled: true
    size: 10Gi

redis:
  enabled: true
  persistence:
    enabled: true

nginx-ingress:
  enabled: true
  controller:
    service:
      type: LoadBalancer

certmanager:
  install: false

prometheus:
  install: false

resources:
  webservice:
    requests:
      cpu: "500m"
      memory: "1.5Gi"
  sidekiq:
    requests:
      cpu: "300m"
      memory: "1Gi"
  postgresql:
    requests:
      cpu: "200m"
      memory: "512Mi"
